const List<String> citiesData = [
  'Baranówka',
  'Czulice',
  'Dojazdów',
  'Głęboka',
  'Goszcza',
  'Goszyce',
  'Karniów',
  'Kocmyrzów',
  'Krzysztoforzyce',
  'Łosokowice',
  'Luborzyca',
  'Łuczyce (część I Krakowska)',
  'Łuczyce (część II Prądnik)',
  'Maciejowice',
  'Marszowice',
  'Pietrzejowice',
  'Prusy',
  'Rawałowice',
  'Sadowie',
  'Skrzeszowice',
  'Sulechów',
  'Wiktorowice',
  'Wilków',
  'Wola Luborzycka',
  'Wysiołek Luborzycki',
  'Zastów'
];

Map<String, List<Map<String, String>>> eventsData = {
  "baranowka": [
    {"date": "2024-12-31", "name": "odpady segregowane"}
  ],
  "czulice": [],
  "dojazdow": [],
  "gleboka": [],
  "goszcza": [],
  "goszyce": [],
  "karniow": [],
  "kocmyrzow": [],
  "krzysztoforzyce": [],
  "losokowice": [
    {"date": "2024-12-31", "name": "odpady segregowane"}
  ],
  "luborzyca": [],
  "luczyce_czesc_i_krakowska": [],
  "luczyce_czesc_ii_pradnik": [],
  "maciejowice": [],
  "marszowice": [],
  "pietrzejowice": [],
  "prusy": [],
  "rawalowice": [],
  "sadowie": [],
  "skrzeszowice": [],
  "sulechow": [],
  "wiktorowice": [],
  "wilkow": [],
  "wola_luborzycka": [],
  "wysiolek_luborzycki": [],
  "zastow": []
};
